dist: trusty
sudo: false

env:
  - TF_INPUT=false

before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"
  - terraform -v

script:
  - terraform init
  - terraform fmt -check=true -write=false
  - terraform validate
